version: '3'

services:
   api:
      image: mern-tasks-backend:latest
      container_name: mern-tasks-backend
      ports:
         - '4004:4004'
      networks:
         - mern-tasks-network

   react:
      image: mern-tasks-frontend:latest
      container_name: mern-tasks-frontend
      ports:
         - '8081:80'
      networks:
         - mern-tasks-network
      depends_on:
         - api

   entriesdb:
      image: mongo:5.0.0
      container_name: mern-tasks-mongodb
      ports:
         - '27018:27017'
      volumes:
         - ./mongo:/data/db
      networks:
         - mern-tasks-network

networks:
   mern-tasks-network:
