version: '3'

services:
   api:
      image: mern-tasks-backend:latest
      ports:
         - '4004:4004'
      networks:
         - mern-tasks-network

   react:
      image: mern-tasks-frontend:latest
      ports:
         - '8081:80'
      networks:
         - mern-tasks-network

networks:
   mern-tasks-network:
